### ISSUE TITLE
How to build the project?

### ISSUE THREAD

**Issue by alebaffa** [hyperledger-labs/yui-corda-ibc#25]
Hi, sorry to open this issue, but I could not find a way to communicate with you for questions.
I tried to build the project (on Ubuntu with WSL2, but I can also try on a Linux VM, in case), but I always get errors.
I tried to do these steps (I already installed rustc, JDK 8, Go, Docker):

- `git submodule update --init`
- `make clean buildClient`

But it gets in error:
```
Caused by:
  process didn't exit successfully: `/home/brain/workspace/yui-corda-ibc/rust/target/release/build/yui-corda-ibc-client-5694ca61e55d9363/build-script-build` (exit code: 1)
  --- stdout
  cargo:rerun-if-changed=../proto/src/main/proto
  cargo:rerun-if-changed=../external/ibc-go/proto
  cargo:rerun-if-changed=../external/ibc-go/third_party/proto
  cargo:rerun-if-changed=../external/yui-fabric-ibc/proto

  --- stderr
  error running rustfmt: Os { code: 2, kind: NotFound, message: "No such file or directory" }
warning: build failed, waiting for other jobs to finish...
error: build failed
make: *** [Makefile:21: buildClient] Error 101
```

Is there a documentation that describes how to build and run the project?

**Comment by siburu** [comment]
Thank you for trying this project!

>  I tried to build the project (on Ubuntu with WSL2, but I can also try on a Linux VM, in case), but I always get errors.

`protoc` and `rustfmt` are the requirements to build the client.
You can know this by checking the following line.
https://github.com/hyperledger-labs/yui-corda-ibc/blob/main/Dockerfiles/yui-corda-ibc-client/Dockerfile#L7

> Is there a documentation that describes how to build and run the project?

Not yet, sorry.
Once the client is built, you can test the current implementation by `make buildImage test`.
This is a test for handshake of connection and channel between two Corda networks.

**Comment by alebaffa** [comment]
Ok understood, thanks! 🙏
