### ISSUE TITLE
 make buildClientImage not working

### ISSUE THREAD

**Issue by neogeo1988** [hyperledger-labs/yui-corda-ibc#32]
OS: ubuntu 20.04

error: failed to run custom build command for `yui-corda-ibc-client v0.1.0 (/usr/src/app/rust)`

Caused by:
  process didn't exit successfully: `/usr/src/app/rust/target/debug/build/yui-corda-ibc-client-d4e47a92dc31de2e/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=../proto/src/main/proto
  cargo:rerun-if-changed=../external/ibc-go/proto
  cargo:rerun-if-changed=../external/ibc-go/third_party/proto
  cargo:rerun-if-changed=../external/yui-fabric-ibc/proto

  --- stderr
  Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
warning: build failed, waiting for other jobs to finish...
error: build failed
make: *** [Makefile:25: buildClient] Error 101
The command '/bin/sh -c make buildClient' returned a non-zero code: 2
make: *** [Makefile:38: buildClientImage] Error 2

**Comment by siburu** [comment]
@neogeo1988 Thank you for trying this product. And I'm sorry for my late response.
I think you can resolve the above issue by executing `git submodule update --init`.
